name: example-app

on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        php: [8.0, 7.4]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: ${{ matrix.php }}
          extensions: zip, curl

      - name: Update composer
        run: composer selfupdate

      - name: Install dependencies
        run: cd ./examples/random-app && composer update --prefer-dist --no-interaction

      - name: Execute tests
        run: cd ./examples/random-app && vendor/bin/phpunit
